# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Nuget

on:
  push:
    tags:
      - '*'

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack Stargazer.Abp.Authentication.JwtBearer.Application.Contracts
      run: dotnet pack ./src/Stargazer.Abp.Authentication.JwtBearer.Application.Contracts -c Release -p:PackageVersion=${{ github.event.release.tag_name }}
    - name: Pack Stargazer.Abp.Authentication.JwtBearer.Application
      run: dotnet pack ./src/Stargazer.Abp.Authentication.JwtBearer.Application -c Release -p:PackageVersion=${{ github.event.release.tag_name }}
    - name: Pack Stargazer.Abp.Authentication.JwtBearer.Application.HttpApi
      run: dotnet pack ./src/Stargazer.Abp.Authentication.JwtBearer.Application.HttpApi -c Release -p:PackageVersion=${{ github.event.release.tag_name }}
      
    - name: Publish Stargazer.Abp.Authentication.JwtBearer.Application.Contracts
      run: dotnet nuget push ./src/Stargazer.Abp.Authentication.JwtBearer.Application.Contracts/bin/Release/Stargazer.Abp.Authentication.JwtBearer.Application.Contracts.*.nupkg --skip-duplicate -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
      
    - name: Publish Stargazer.Abp.Authentication.JwtBearer.Application
      run: dotnet nuget push ./src/Stargazer.Abp.Authentication.JwtBearer.Application/bin/Release/Stargazer.Abp.Authentication.JwtBearer.Application.*.nupkg --skip-duplicate -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
      
    - name: Publish Stargazer.Abp.Authentication.JwtBearer.Application.HttpApi
      run: dotnet nuget push ./src/Stargazer.Abp.Authentication.JwtBearer.Application.HttpApi/bin/Release/Stargazer.Abp.Authentication.JwtBearer.Application.HttpApi.*.nupkg --skip-duplicate -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
  
